import { PocketProvider } from "@/providers/pocket-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/providers/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Clinica",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<PocketProvider>
					<AuthProvider>{children}</AuthProvider>
				</PocketProvider>
			</body>
		</html>
	);
}
